
name: ML Run (Docker)
# on mentions a trigger for the workflow
on: 
    push: # when a push is made to the main branch of the repository
      branches:
           - main
jobs:
  ml_run:
    runs-on: ubuntu-latest # runs the workflow on the latest ubuntu version
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # uses the checkout action to checkout the code

      - name: Build Docker image
        run: docker build -t ml-example .


      - name: Run code
        run: docker run --rm ml-example
